spring.application.name=knowledgebase
server.port=8080

# DeepSeek Configuration via Spring AI
spring.ai.openai.api-key=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
#spring.ai.openai.api-key=AIzaSyCjZMfe42Oo1H8CkQ_aNrC5WS_GzuluylI
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.chat.options.model=google/gemma-3-27b-it:free
#spring.ai.openai.chat.options.model=meta-llama/llama-3.3-70b-instruct:free

# We will use local, in-memory embeddings for this guide to avoid API costs
spring.ai.retry.max-attempts=1