spring.application.name=knowledgebase
server.port=8080

spring.ai.openai.api-key=YOUR_API_KEY_HERE
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.chat.options.model=google/gemma-3-27b-it:free
